[tool.poetry]
name = "elfragmentador-data"
version = "0.1.0"
description = ""
authors = ["Jspaezp <jspaezp@gmail.com>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.9"
snakemake = "^6.1.0"
pandas = "^1.2.3"
elfragmentador = {git = "https://github.com/jspaezp/elfragmentador.git", rev = "main"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
