[tool.poetry]
name = "elfragmentador-data"
version = "0.1.0"
description = ""
authors = ["Jspaezp <jspaezp@gmail.com>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
snakemake = "^6.1.0"
pandas = "^1.2.3"
elfragmentador = {git = "https://github.com/jspaezp/elfragmentador.git", rev = "main"}
llvmlite = "^0.36.0"
mokapot = "^0.7.1"
pyteomics = "^4.4.2"
matplotlib = "^3.4.1"
lxml = "^4.6.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
