---
title: "R Notebook"
output:
  html_document:
    df_print: paged
params:
  psms_ef: ~/git/elfragmentador-data/mokapot/PEPTIDOME_EF2.mokapot.psms.txt
  psms: ~/git/elfragmentador-data/mokapot/PEPTIDOME.mokapot.psms.txt
---

```{r, setup, include=FALSE}
# set this option in the first code chunk in the document
knitr::opts_chunk$set(echo = params$printcode)
```

```{r}
library(tidyverse)
theme_set(theme_bw())
```

```{r}
get_scores <- function(x, added_name) {
    df <- readr::read_tsv(x) %>%
        arrange(`mokapot PEP`)

    df$Sample <- added_name
    df <- select(df, `mokapot score`, `mokapot PEP`, Sample, Label)
    return(df)
}

get_roc_curves <- function(x, added_name) {
    df <- readr::read_tsv(x) %>%
        arrange(`mokapot PEP`)

    df$Sample <- added_name
    df[["Accepted Target PSMS"]] <- cumsum(df$Label)
    df <- select(df, `Accepted Target PSMS`, `mokapot PEP`, Sample)
    return(df)
}

df <- bind_rows(
    get_roc_curves(params$psms_ef, "Mokapot + ElFragmentador"),
    get_roc_curves(params$psms, "Mokapot")
)

```

```{r}
head(df)
```
```{r}
num_psm_1 <- df %>% 
  group_by(Sample) %>%
  top_n(1, -abs(0.01 - `mokapot PEP`))

num_psm_1 %>% 
  ungroup() %>%
  mutate(
    label=paste0(
      `Accepted Target PSMS`,
      ": +",
      format(
        (100 * `Accepted Target PSMS` / min(`Accepted Target PSMS`) - 100),
        digits=2),
      "%")) %>%
  ggplot(
    aes(x = Sample,
        y = `Accepted Target PSMS`,
        fill=Sample,
        label=label)) +
  geom_col() +
  geom_text(nudge_y = 500) +
  ggtitle("Number of accepted PSMs", "At 1% FDR")

```


```{r roc_curve, fig.height=3, fig.width=7}
df %>% arrange(`mokapot PEP`) %>%
    filter(`mokapot PEP` < 0.07) %>%
    ggplot(
        aes(
            x = `mokapot PEP`,
            y = `Accepted Target PSMS`,
            colour = Sample)) +
    geom_line() +
    coord_cartesian(xlim = c(0, 0.05))
```

```{r score_density, fig.height=3, fig.width=5}
df <- bind_rows(
    get_scores(params$psms_ef, "ElFragmentador"),
    get_scores(params$psms, "Mokapot + ElFragmentador")
)

ggplot(df, aes(x = `mokapot score`, fill=Sample)) +
  geom_density(alpha = 0.3)
```

