---
title: "R Notebook"
output:
  html_document:
    df_print: paged
params:
  elfragmentador_pin: ~/git/elfragmentador-data/ef_comet_pin/20170430_HeLa_phosp_DDA_B_01_170506194651.elfragmentador.pin
  decoy_psms_ef: ~/git/elfragmentador-data/ef_mokapot/Phospho.elfragmentador.mokapot.decoy.psms.txt
  decoy_psms: ~/git/elfragmentador-data/mokapot/Phospho.mokapot.decoy.psms.txt
  psms_ef: ~/git/elfragmentador-data/ef_mokapot/Phospho.elfragmentador.mokapot.psms.txt
  psms: ~/git/elfragmentador-data/mokapot/Phospho.mokapot.psms.txt
  model_importance: ~/git/elfragmentador-data/mokapot/Phospho.mokapot.weights.csv
  model_importance_ef: ~/git/elfragmentador-data/ef_mokapot/Phospho.elfragmentador.mokapot.weights.csv
  output_swapped_psms: swapped_psms.csv
  output_top_swapped_psms: swapped_psms.csv
  output_best_corr_psms: best_corr_psms.csv

---

```{r, setup, include=FALSE}
# set this option in the first code chunk in the document
knitr::opts_chunk$set(echo = params$printcode)

```

```{r}
print(params)
library(tidyverse)
library(hexbin)
theme_set(theme_bw())
```


```{r}
files <- unlist(strsplit(params$elfragmentador_pin, split="\\s+"), use.names = FALSE)

pin_df <- bind_rows(purrr::map(files, readr::read_tsv))

pin_df <- mutate(
    pin_df, 
    Label = ifelse(Label > 0, yes = "Target", no = "Decoy"))

colnames(pin_df)
```

```{r}
head(pin_df)
```

```{r scores_vs_corr}
ggplot(pin_df, aes(x = Xcorr, y = SpecAngle, colour = factor(Label))) +
    geom_point(alpha = 1, shape = ".")

ggplot(pin_df, aes(x = log2(Sp + 1), y = SpecAngle, colour = factor(Label))) +
    geom_point(alpha = 1, shape = ".") 

ggplot(pin_df, aes(x = lnExpect, y = SpecAngle, colour = factor(Label))) +
    geom_point(alpha = 1, shape = ".")

```

```{r fig.height=4, fig.width=5}

ggplot(pin_df, aes(x = lnExpect, fill = factor(Label))) +
  geom_histogram(alpha = 0.7, shape = ".") +
  facet_wrap(~Label, ncol = 1) + scale_y_sqrt()

ggplot(pin_df, aes(x = Xcorr, fill = factor(Label))) +
  geom_histogram(alpha = 0.7, shape = ".") +
  facet_wrap(~Label, ncol = 1) + scale_y_sqrt()

ggplot(pin_df, aes(x = SpecAngle, fill = factor(Label))) +
  geom_histogram(alpha = 0.7, shape = ".") +
  facet_wrap(~Label, ncol = 1) + scale_y_sqrt()


ggplot(pin_df, aes(x = DiffNormRT, fill = factor(Label))) +
  geom_histogram(alpha = 0.7, shape = ".") +
  facet_wrap(~Label, ncol = 1) + scale_y_sqrt() +
  scale_y_sqrt()


```


```{r scores_cs_corr2}
ggplot(
    pin_df, 
    aes(
        y = Xcorr,
        x = SpecAngle)) +
    geom_hex(bins=100) + 
    facet_wrap(~ Label) +
    scale_fill_viridis_c(trans="sqrt")

ggplot(
    pin_df, 
    aes(
        y = deltCn,
        x = SpecAngle)) +
    geom_hex(bins=50) + 
    facet_wrap(~ Label) +
    scale_fill_viridis_c(direction = -1, trans="sqrt")


ggplot(
    pin_df, 
    aes(
        y = deltLCn,
        x = SpecAngle)) +
    geom_hex(bins=50) + 
    facet_wrap(~ Label) +
    scale_fill_viridis_c(direction = -1, trans="sqrt")
```

```{r}
pin_df %>% filter(Xcorr > 5)
```

```{r}
best_corr_peps <- pin_df %>%
  filter(Label == "Target", lnExpect < -10) %>%
  group_by(ScanNr, ExpMass) %>% top_n(1, SpecAngle) %>% ungroup() %>%
  group_by(Peptide) %>% top_n(1, SpecAngle) %>% ungroup() %>%
  group_by(Modified = grepl("\\[", Peptide)) %>%
  top_n(10, SpecAngle)
best_corr_peps
write_csv(best_corr_peps, params$output_best_corr_psms)
```


```{r scores_vs_corr3}
# ggplot(
#     pin_df, 
#     aes(
#         y = Xcorr,
#         x = SpecAngle)) +
#     geom_density_2d_filled(bins=20) + 
#     theme(legend.position = "None") +
#     facet_wrap(~ Label) 
# 
# 
# ggplot(
#     pin_df, 
#     aes(
#         y = Sp,
#         x = SpecAngle)) +
#     geom_density_2d_filled(bins=200, contour_var = "ndensity") + 
#     theme(legend.position = "None") +
#     facet_wrap(~ Label) + scale_y_sqrt() 
```


```{r}
df <- bind_rows(
    readr::read_tsv( params$psms_ef ) %>% select(-Proteins),
    readr::read_tsv( params$decoy_psms_ef ) %>% select(-Proteins)
    )


df2 <- bind_rows(
    readr::read_tsv( params$psms ) %>% select(-Proteins),
    readr::read_tsv( params$decoy_psms ) %>% select(-Proteins)
    )

df_joint <- df %>% full_join(
    df2,
    by = c(
        "SpecId", "Label", "ScanNr",
        "ExpMass", "CalcMass",
        "Peptide"),
    suffix = c(".EF", ".None")) %>%
    mutate(Label = ifelse(Label, yes = "Target", no = "Decoy"))
```

```{r}
head(df_joint)
```

```{r scores_pre_post}
ggplot(
    df_joint,
    aes(
        x = `mokapot PEP.None`,
        y = `mokapot PEP.EF`)) +
    geom_hex(bins=20)  +
    facet_wrap(~ Label) +
    scale_fill_viridis_c(trans = "log1p")


ggplot(
    df_joint %>%
        filter(`mokapot PEP.None` < 0.05 | `mokapot PEP.EF` < 0.05 ),
    aes(
        x = `mokapot PEP.None`,
        y = `mokapot PEP.EF`)) +
    geom_hex(bins=20)  +
    facet_wrap(~ Label) +
    scale_fill_viridis_c(trans = "log1p")
```


```{r}
swapped_df_joint <- df_joint %>%
    filter(`mokapot PEP.None` < 0.01 | `mokapot PEP.EF` < 0.01) %>%
    filter(`mokapot PEP.None` > 0.01 | `mokapot PEP.EF` > 0.01)

write_csv(swapped_df_joint, params$output_swapped_psms)

swapped_df_joint %>% arrange(`mokapot PEP.EF`) %>% head(200)

```



```{r}
top_changing <- filter(
  pin_df,
  SpecId %in% filter(swapped_df_joint,
  `mokapot PEP.EF` <= 0.01)$SpecId,
  PepLen < 25) %>% 
  left_join(swapped_df_joint) %>%
  mutate(
      diff_mokapot_score = `mokapot score.EF` - `mokapot score.None`) %>%
  arrange(-diff_mokapot_score) %>%
  filter(Label == "Target") %>%
  group_by(ScanNr, ExpMass) %>% top_n(1, SpecAngle) %>% ungroup() %>%
  group_by(Peptide) %>% top_n(1, diff_mokapot_score) %>% ungroup() %>%
  group_by(Modified = grepl("\\[", Peptide)) %>%
  top_n(10, diff_mokapot_score) %>%
  ungroup()

write_csv(top_changing, params$output_top_swapped_psms)
print(top_changing)

paste(top_changing$ScanNr, collapse = ", ")
paste(top_changing$Peptide %>% gsub("^.\\.|\\..$", "", .), collapse = "', '")
```


```{r}
top_5_xcorr <- top_n(pin_df, 5, Xcorr)
print(top_5_xcorr)
paste(top_5_xcorr$ScanNr, sep = "'",collapse = ", ")
paste(top_5_xcorr$Peptide %>% gsub("^.\\.|\\..$", "", .), collapse = "', '", sep = "'")
```


```{r}
ggplot(
    pin_df,
    aes(
        y = Xcorr,
        x = SpecAngle)) +
    geom_hex(bins=100) + 
    facet_wrap(~ Label) +
    scale_fill_viridis_c(trans="sqrt", alpha = 0.4) +
    geom_point(
        color = "red",
        size = 0.2,
        data = filter(
            pin_df,
            SpecId %in% filter(swapped_df_joint, `mokapot PEP.EF` > 0.01)$SpecId)) +
    geom_point(
        color = "black",
        size = 0.2,
        data = filter(
            pin_df,
            SpecId %in% filter(swapped_df_joint, `mokapot PEP.EF` <= 0.01)$SpecId)) +
    geom_point(
        color = "blue",
        size = 3,
        data = filter(
            pin_df,
            SpecId %in% top_changing$SpecId))
  

ggplot(
    pin_df,
    aes(
        y = lnExpect,
        x = SpecAngle)) +
    geom_hex(bins=100) + 
    facet_wrap(~ Label) +
    scale_fill_viridis_c(trans="sqrt", alpha = 0.4) +
    geom_point(
        color = "red",
        size = 0.2,
        data = filter(
            pin_df,
            SpecId %in% filter(swapped_df_joint, `mokapot PEP.EF` > 0.01)$SpecId)) +
    geom_point(
        color = "black",
        size = 0.2,
        data = filter(
            pin_df,
            SpecId %in% filter(swapped_df_joint, `mokapot PEP.EF` <= 0.01)$SpecId)) +
    geom_point(
        color = "blue",
        size = 3,
        data = filter(
            pin_df,
            SpecId %in% top_changing$SpecId))
    

```

```{r}
ggplot(
    pin_df,
    aes(
        y = Xcorr,
        x = DiffNormRT)) +
    geom_hex(bins=100) + 
    facet_wrap(~ Label) +
    scale_fill_viridis_c(trans="sqrt", alpha = 0.4) +
    geom_point(
        color = "red",
        size = 0.2,
        data = filter(
            pin_df,
            SpecId %in% filter(swapped_df_joint, `mokapot PEP.EF` > 0.01)$SpecId)) +
    geom_point(
        color = "black",
        size = 0.2,
        data = filter(
            pin_df,
            SpecId %in% filter(swapped_df_joint, `mokapot PEP.EF` <= 0.01)$SpecId)) +
    geom_point(
        color = "blue",
        size = 3,
        data = filter(
            pin_df,
            SpecId %in% top_changing$SpecId))
  

ggplot(
    pin_df,
    aes(
        y = lnExpect,
        x = DiffNormRT)) +
    geom_hex(bins=100) + 
    facet_wrap(~ Label) +
    scale_fill_viridis_c(trans="sqrt", alpha = 0.4) +
    geom_point(
        color = "red",
        size = 0.2,
        data = filter(
            pin_df,
            SpecId %in% filter(swapped_df_joint, `mokapot PEP.EF` > 0.01)$SpecId)) +
    geom_point(
        color = "black",
        size = 0.2,
        data = filter(
            pin_df,
            SpecId %in% filter(swapped_df_joint, `mokapot PEP.EF` <= 0.01)$SpecId)) +
    geom_point(
        color = "blue",
        size = 3,
        data = filter(
            pin_df,
            SpecId %in% top_changing$SpecId))
    

```

```{r fig.height=3, fig.width=6}
base_lm <- function(data) {
  return(lm(Weight ~ Rescoring, data=data))
}

base_lm <- purrr::safely(base_lm)

pull_p <-  purrr::safely(function(safe_lm) {
  summary(safe_lm$result)$coefficients[2,4]
})

importances <- bind_rows(
  readr::read_csv(params$model_importance) %>% 
      mutate(Rescoring = "Standard") ,
  readr::read_csv(params$model_importance_ef) %>% 
      mutate(Rescoring = "ElFragmentador")) %>%
  filter(Feature != "intercept") %>%
  complete(Feature, Fold, Rescoring, fill=list(Weight = 0)) %>%
  group_by(Feature) %>%
  nest() %>%
  mutate(lm_res = purrr::map(data, base_lm)) %>%
  mutate(lm_p = purrr::map(lm_res, pull_p)) %>%
  mutate(p = purrr::map_dbl(lm_p, ~ .x$result)) %>%
  unnest(data)

signif_importances <- importances %>%
  filter(p < 0.05) %>% 
  group_by(Feature) %>% 
  arrange(max(abs(Weight)))

signif_importances$Feature = with(signif_importances, reorder(Feature, abs(Weight)))


ggplot(
  signif_importances, 
  aes(y=Feature, x=abs(Weight), colour=Rescoring)) +
  geom_line(alpha =0.1, size=2, aes(colour=NULL, fill=NULL)) +
  geom_boxplot(
    position = position_dodge(width=0.2), width = 0.8) +
    ggtitle("Absolute Normalized feature\nweights in the Mokapot model") 



```

